version: '3.8'
services:
  quarkus-keycloak:
    image: jboss/keycloak:15.0.2
    command:
      [
          '-b',
          '0.0.0.0',
          '-Dkeycloak.migration.action=import',
          '-Dkeycloak.migration.provider=dir',
          '-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config',
          '-Dkeycloak.migration.strategy=OVERWRITE_EXISTING',
          '-Djboss.socket.binding.port-offset=1000',
          '-Dkeycloak.profile.feature.upload_scripts=enabled',
      ]
    volumes:
      - ./realm-config:/opt/jboss/keycloak/realm-config
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=POSTGRES
      - DB_ADDR=quarkus-postgresql
      - DB_DATABASE=keycloak_quarkus_db
      - DB_PORT=5432
      - DB_SCHEMA=keycloak_schema
      - DB_USER=quarkususer
      - DB_PASSWORD=quarkuspass
    ports:
      - 9080:9080
      - 127.0.0.1:9443:9443
      - 127.0.0.1:10990:10990
